# Icon font definition for Nexus client
module = "icon"

[glyphs]
bookmark = "fontawesome-bookmark"
chat = "fontawesome-chat"
close = "fontawesome-cancel"
cog = "fontawesome-cog"
collapse_left = "fontawesome-collapse-left"
expand_right = "fontawesome-expand-right"
info = "fontawesome-info"
kick = "fontawesome-logout"
logout = "fontawesome-logout"
megaphone = "fontawesome-megaphone"
message = "fontawesome-chat"
sun = "fontawesome-sun"
user_plus = "fontawesome-user-plus"
users = "fontawesome-users"
