# Icon font definition for Nexus client
module = "icon"

[glyphs]
chat = "fontawesome-chat"
cog = "fontawesome-cog"
collapse_left = "fontawesome-collapse-left"
expand_right = "fontawesome-expand-right"
logout = "fontawesome-logout"
megaphone = "fontawesome-megaphone"
sun = "fontawesome-sun"
user_plus = "fontawesome-user-plus"
users = "fontawesome-users"