[package]
name = "nexus-common"
version = "0.4.0"
edition = "2024"

[dependencies]
rand = "0.9"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["io-util", "macros", "rt"] }

[lib]
name = "nexus_common"
path = "src/lib.rs"