[package]
name = "nexus-common"
version = "0.1.0"
edition = "2024"

[dependencies]
ipnet = "2.10"
once_cell = "1.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "nexus_common"
path = "src/lib.rs"