[package]
name = "nexus-common"
version = "0.3.0"
edition = "2024"

[dependencies]
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["io-util"] }

[lib]
name = "nexus_common"
path = "src/lib.rs"